#spring.application.name=cafe-inventory

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/cms
spring.datasource.username=postgres
spring.datasource.password=postgres